// Code generated by MockGen. DO NOT EDIT.
// Source: approval_template_step_repository.go
//
// Generated by this command:
//
//	mockgen -source=approval_template_step_repository.go -destination=mock_approval_template_step_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/taufiktriantono/api-first-monorepo/internal/approvals/v1/domain"
	repository "github.com/taufiktriantono/api-first-monorepo/pkg/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockApprovalTemplateStepRepository is a mock of ApprovalTemplateStepRepository interface.
type MockApprovalTemplateStepRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalTemplateStepRepositoryMockRecorder
	isgomock struct{}
}

// MockApprovalTemplateStepRepositoryMockRecorder is the mock recorder for MockApprovalTemplateStepRepository.
type MockApprovalTemplateStepRepositoryMockRecorder struct {
	mock *MockApprovalTemplateStepRepository
}

// NewMockApprovalTemplateStepRepository creates a new mock instance.
func NewMockApprovalTemplateStepRepository(ctrl *gomock.Controller) *MockApprovalTemplateStepRepository {
	mock := &MockApprovalTemplateStepRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalTemplateStepRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalTemplateStepRepository) EXPECT() *MockApprovalTemplateStepRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockApprovalTemplateStepRepository) BatchCreate(ctx context.Context, resources []*domain.ApprovalTemplateStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) BatchCreate(ctx, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).BatchCreate), ctx, resources)
}

// Count mocks base method.
func (m *MockApprovalTemplateStepRepository) Count(ctx context.Context, f *domain.ApprovalTemplateStep) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m *MockApprovalTemplateStepRepository) Create(ctx context.Context, resource *domain.ApprovalTemplateStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockApprovalTemplateStepRepository) Delete(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) Delete(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).Delete), ctx, resourceID)
}

// Find mocks base method.
func (m *MockApprovalTemplateStepRepository) Find(ctx context.Context, f *domain.ApprovalTemplateStep, opts ...repository.QueryOption) ([]*domain.ApprovalTemplateStep, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*domain.ApprovalTemplateStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockApprovalTemplateStepRepository) FindOne(ctx context.Context, f *domain.ApprovalTemplateStep) (*domain.ApprovalTemplateStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, f)
	ret0, _ := ret[0].(*domain.ApprovalTemplateStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) FindOne(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).FindOne), ctx, f)
}

// Update mocks base method.
func (m *MockApprovalTemplateStepRepository) Update(ctx context.Context, resourceID string, resource *domain.ApprovalTemplateStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resourceID, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) Update(ctx, resourceID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).Update), ctx, resourceID, resource)
}

// WithTrx mocks base method.
func (m *MockApprovalTemplateStepRepository) WithTrx(tx *gorm.DB) ApprovalTemplateStepRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTrx", tx)
	ret0, _ := ret[0].(ApprovalTemplateStepRepository)
	return ret0
}

// WithTrx indicates an expected call of WithTrx.
func (mr *MockApprovalTemplateStepRepositoryMockRecorder) WithTrx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTrx", reflect.TypeOf((*MockApprovalTemplateStepRepository)(nil).WithTrx), tx)
}
