// Code generated by MockGen. DO NOT EDIT.
// Source: approval_repository.go
//
// Generated by this command:
//
//	mockgen -source=approval_repository.go -destination=mock_approval_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/taufiktriantono/api-first-monorepo/internal/approvals/v1/domain"
	option "github.com/taufiktriantono/api-first-monorepo/pkg/db/option"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockApprovalRepository is a mock of ApprovalRepository interface.
type MockApprovalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalRepositoryMockRecorder
	isgomock struct{}
}

// MockApprovalRepositoryMockRecorder is the mock recorder for MockApprovalRepository.
type MockApprovalRepositoryMockRecorder struct {
	mock *MockApprovalRepository
}

// NewMockApprovalRepository creates a new mock instance.
func NewMockApprovalRepository(ctrl *gomock.Controller) *MockApprovalRepository {
	mock := &MockApprovalRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalRepository) EXPECT() *MockApprovalRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockApprovalRepository) Count(ctx context.Context, f *domain.Approval) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockApprovalRepositoryMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockApprovalRepository)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m *MockApprovalRepository) Create(ctx context.Context, resource *domain.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalRepositoryMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalRepository)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockApprovalRepository) Delete(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalRepositoryMockRecorder) Delete(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalRepository)(nil).Delete), ctx, resourceID)
}

// Find mocks base method.
func (m *MockApprovalRepository) Find(ctx context.Context, f *domain.Approval, opts ...option.QueryOption) ([]*domain.Approval, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*domain.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockApprovalRepositoryMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockApprovalRepository)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockApprovalRepository) FindOne(ctx context.Context, f *domain.Approval) (*domain.Approval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, f)
	ret0, _ := ret[0].(*domain.Approval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalRepositoryMockRecorder) FindOne(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalRepository)(nil).FindOne), ctx, f)
}

// Update mocks base method.
func (m *MockApprovalRepository) Update(ctx context.Context, resourceID string, resource *domain.Approval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resourceID, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalRepositoryMockRecorder) Update(ctx, resourceID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalRepository)(nil).Update), ctx, resourceID, resource)
}

// WithTrx mocks base method.
func (m *MockApprovalRepository) WithTrx(tx *gorm.DB) ApprovalRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTrx", tx)
	ret0, _ := ret[0].(ApprovalRepository)
	return ret0
}

// WithTrx indicates an expected call of WithTrx.
func (mr *MockApprovalRepositoryMockRecorder) WithTrx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTrx", reflect.TypeOf((*MockApprovalRepository)(nil).WithTrx), tx)
}
