// Code generated by MockGen. DO NOT EDIT.
// Source: approval_step_repository.go
//
// Generated by this command:
//
//	mockgen -source=approval_step_repository.go -destination=mock_approval_step_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/taufiktriantono/api-first-monorepo/internal/approvals/v1/domain"
	repository "github.com/taufiktriantono/api-first-monorepo/pkg/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockApprovalStepRepository is a mock of ApprovalStepRepository interface.
type MockApprovalStepRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalStepRepositoryMockRecorder
	isgomock struct{}
}

// MockApprovalStepRepositoryMockRecorder is the mock recorder for MockApprovalStepRepository.
type MockApprovalStepRepositoryMockRecorder struct {
	mock *MockApprovalStepRepository
}

// NewMockApprovalStepRepository creates a new mock instance.
func NewMockApprovalStepRepository(ctrl *gomock.Controller) *MockApprovalStepRepository {
	mock := &MockApprovalStepRepository{ctrl: ctrl}
	mock.recorder = &MockApprovalStepRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalStepRepository) EXPECT() *MockApprovalStepRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockApprovalStepRepository) Count(ctx context.Context, f *domain.ApprovalStep) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockApprovalStepRepositoryMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockApprovalStepRepository)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m *MockApprovalStepRepository) Create(ctx context.Context, resource *domain.ApprovalStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApprovalStepRepositoryMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApprovalStepRepository)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockApprovalStepRepository) Delete(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApprovalStepRepositoryMockRecorder) Delete(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApprovalStepRepository)(nil).Delete), ctx, resourceID)
}

// Find mocks base method.
func (m *MockApprovalStepRepository) Find(ctx context.Context, f *domain.ApprovalStep, opts ...repository.QueryOption) ([]*domain.ApprovalStep, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*domain.ApprovalStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockApprovalStepRepositoryMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockApprovalStepRepository)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockApprovalStepRepository) FindOne(ctx context.Context, f *domain.ApprovalStep) (*domain.ApprovalStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, f)
	ret0, _ := ret[0].(*domain.ApprovalStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApprovalStepRepositoryMockRecorder) FindOne(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApprovalStepRepository)(nil).FindOne), ctx, f)
}

// Update mocks base method.
func (m *MockApprovalStepRepository) Update(ctx context.Context, resourceID string, resource *domain.ApprovalStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resourceID, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApprovalStepRepositoryMockRecorder) Update(ctx, resourceID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApprovalStepRepository)(nil).Update), ctx, resourceID, resource)
}

// WithTrx mocks base method.
func (m *MockApprovalStepRepository) WithTrx(tx *gorm.DB) ApprovalStepRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTrx", tx)
	ret0, _ := ret[0].(ApprovalStepRepository)
	return ret0
}

// WithTrx indicates an expected call of WithTrx.
func (mr *MockApprovalStepRepositoryMockRecorder) WithTrx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTrx", reflect.TypeOf((*MockApprovalStepRepository)(nil).WithTrx), tx)
}
