name: Migrate DB

on:
  push:
    paths:
      - 'migrations/**'
      - '.github/workflows/db-migrate.yml'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - domain: approval
            db:    ${{ secrets.APPROVAL_DB_URL }}
            
          - domain: transaction
            db:    ${{ secrets.TRANSACTION_DB_URL }}
    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://…/migrate.linux-amd64.tar.gz | tar xz && sudo mv migrate /usr/local/bin/
      - run: ./scripts/migrate.sh ${{ matrix.domain }} ${{ matrix.db }}

